site: developers.zone
title: developers.zone
greetings: developers.zone
description: >-
  personal tech blog of Kristijan Rusu
lang: en-US
timezone: Europe/Skopje
repo: https://github.com/kristijan-rusu/developers.zone # site repo [optional]
data-theme: light # default theme "dark" | "light"
discus-identifier:

author:
  name: Kritijan Rusu
  bio: just a minimalist, personal blog
  userpicture:
  username: # general username
  github: https://github.com/kristijan-rusu/ # github username
  twitter: # twitter username
  linkedin: https://www.linkedin.com/in/kristijan-rusu/ # linkedin username
  email: kristijan.rusu@gmail.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
domain: developers.zone
url: https://developers.zone # Domain Name of host. [username].github.io for github pages
baseurl:  # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  #  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false


